from building import *

cwd     = os.path.join(str(Dir('#')), 'protocol808')
src	= Glob('*.c')+Glob('*.h')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('protocol808', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
